$('.owl-carousel').owlCarousel({    
    loop:true,
    margin:1,    
    autoplay:true,
    autoplayTimeout:2000,
    autoplayHoverPause:true,
    autoWidth:true,        
    responsive:{
        0:{
            items:1
        },
        600:{
            items:3
        },
        1000:{
            items:5
        }
    }
})