$('.owl-carousel').owlCarousel({    
    loop:true,
    margin:1,    
    autoplay:true,    
    autoplayHoverPause:true,
    autoWidth:true,        
    nav: false,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:3
        },
        1000:{
            items:5
        }
    }
})